# Generated by Django 5.2.6 on 2025-11-11 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0004_counsellorprofile_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnavailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='unavailable date')),
                ('reason', models.CharField(blank=True, help_text="Optional reason for unavailability (e.g., 'Holiday', 'Personal leave')", max_length=255, null=True, verbose_name='reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('counsellor', models.ForeignKey(limit_choices_to={'role': 'counsellor'}, on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_dates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unavailable Date',
                'verbose_name_plural': 'Unavailable Dates',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['counsellor', 'date'], name='apps_accoun_counsel_095e4b_idx')],
                'unique_together': {('counsellor', 'date')},
            },
        ),
    ]
