# Generated by Django 5.2.6 on 2025-11-09 11:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(verbose_name='appointment date and time')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='duration in minutes')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='appointment fee')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='payment status')),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razorpay order ID')),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razorpay payment ID')),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razorpay signature')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='appointment status')),
                ('google_meet_link', models.URLField(blank=True, null=True, verbose_name='Google Meet link')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('feedback_submitted', models.BooleanField(default=False, verbose_name='feedback submitted')),
                ('feedback_submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='feedback submitted at')),
                ('feedback_form_url', models.URLField(blank=True, null=True, verbose_name='feedback form URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to=settings.AUTH_USER_MODEL)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counsellor_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-appointment_date'],
                'indexes': [models.Index(fields=['client', 'appointment_date'], name='appointment_client__903153_idx'), models.Index(fields=['counsellor', 'appointment_date'], name='appointment_counsel_8a8702_idx'), models.Index(fields=['payment_status'], name='appointment_payment_79f9ef_idx'), models.Index(fields=['status'], name='appointment_status_8fe9d7_idx')],
            },
        ),
    ]
