# Generated by Django 5.2.6 on 2025-11-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0003_remove_counsellorprofile_bio_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellorprofile',
            name='experience',
            field=models.TextField(blank=True, help_text="Free-form experience description (e.g. '10 years in CBT, special focus on anxiety')", null=True, verbose_name='experience'),
        ),
    ]
